/** 감사 action 코드 → 사람이 읽는 라벨/아이콘 — 운영·기관 감사 화면 공용.
 * 백엔드가 실제로 기록하는 코드 전부를 매핑한다 (grep 'action="' 기준).
 * 매핑에 없는 코드는 화면 fallback으로 원문(영문)이 노출되므로 누락 없이 유지할 것. */
export const AUDIT_ACTION_META: Record<string, { label: string; icon: string; cls: string }> = {
  // 운영자 — 기관 가입 승인 콘솔
  org_registration_approved: { label: '기관 가입 승인', icon: 'ph-check-circle', cls: 'ok' },
  org_registration_rejected: { label: '기관 가입 거절', icon: 'ph-x-circle', cls: 'no' },
  // 기관 관리자
  'org.update': { label: '기관 정보 수정', icon: 'ph-pencil-simple', cls: 'neutral' },
  'org.teacher_add': { label: '선생님 추가', icon: 'ph-user-plus', cls: 'ok' },
  'org.teacher_update': { label: '선생님 정보 수정', icon: 'ph-pencil-simple', cls: 'neutral' },
  'org.teacher_delete': { label: '선생님 삭제', icon: 'ph-user-minus', cls: 'no' },
  'org.teacher_invite': { label: '선생님 초대', icon: 'ph-envelope-simple', cls: 'ok' },
  'org.captcha_settings_update': { label: '캡차 설정 변경', icon: 'ph-shield-check', cls: 'neutral' },
  'org.student_code_reissue': { label: '학생 가입코드 재발급', icon: 'ph-arrows-clockwise', cls: 'neutral' },
  'student.password_reset': { label: '학생 비밀번호 초기화', icon: 'ph-key', cls: 'warn' },
  'student.parent_invite': { label: '학부모 초대코드 발급', icon: 'ph-user-circle-plus', cls: 'ok' },
  'parent_link.revoke': { label: '학부모 연결 해제(기관)', icon: 'ph-link-break', cls: 'warn' },
  'student.assign_class': { label: '학생 학급 배정', icon: 'ph-users-three', cls: 'neutral' },
  // 학부모
  'parent.profile_update': { label: '학부모 프로필 수정', icon: 'ph-pencil-simple', cls: 'neutral' },
  'parent.child_link': { label: '자녀 연결', icon: 'ph-link', cls: 'ok' },
  'parent.child_unlink': { label: '자녀 연결 해제', icon: 'ph-link-break', cls: 'warn' },
  'parent.child_settings_update': { label: '자녀 설정 변경', icon: 'ph-sliders-horizontal', cls: 'neutral' },
  // 선생님
  'teacher.profile_update': { label: '선생님 프로필 수정', icon: 'ph-pencil-simple', cls: 'neutral' },
  'teacher.class_student_add': { label: '학급 학생 추가', icon: 'ph-user-plus', cls: 'ok' },
  'teacher.class_student_update': { label: '학급 학생 수정', icon: 'ph-pencil-simple', cls: 'neutral' },
  'teacher.class_student_remove': { label: '학급 학생 제외', icon: 'ph-user-minus', cls: 'no' },
  // 공용 설정/계정
  'settings.update': { label: '설정 변경', icon: 'ph-gear', cls: 'neutral' },
  'settings.change_password': { label: '비밀번호 변경', icon: 'ph-key', cls: 'warn' },
  'settings.account_delete': { label: '계정 삭제(탈퇴)', icon: 'ph-user-minus', cls: 'no' },
  // 운영자 — 문의 처리
  'inquiry.answer': { label: '문의 답변 발송', icon: 'ph-paper-plane-tilt', cls: 'ok' },
  'inquiry.resolve': { label: '문의 처리 완료', icon: 'ph-check-circle', cls: 'ok' },
  // 운영자 — 행동 데이터 학습셋 관리
  'behavior.dataset_mark': { label: '행동 데이터 학습셋 상태 변경', icon: 'ph-fingerprint', cls: 'neutral' },
  'behavior.export': { label: '행동 데이터 내보내기', icon: 'ph-download-simple', cls: 'neutral' },
  // 운영자 — 기관 관리
  'org.create': { label: '기관 추가', icon: 'ph-buildings', cls: 'ok' },
  'org.delete': { label: '기관 삭제', icon: 'ph-trash', cls: 'no' },
  'org.code_rotate': { label: '기관 코드 재발급', icon: 'ph-arrows-clockwise', cls: 'warn' },
  'org.admin_credentials_sent': { label: '기관 관리자 임시비번 발송', icon: 'ph-envelope-simple', cls: 'warn' },
  'org.entitlements_set': { label: '기관 요금제/권한 변경', icon: 'ph-credit-card', cls: 'neutral' },
  // 운영자 — API 키
  'captcha.api_key_issue': { label: 'API 키 발급', icon: 'ph-key', cls: 'ok' },
  'captcha.api_key_revoke': { label: 'API 키 폐기', icon: 'ph-key', cls: 'no' },
  'captcha.api_key_rotate': { label: 'API 키 시크릿 재발급', icon: 'ph-arrows-clockwise', cls: 'warn' },
  // 운영자 — 운영자 계정 관리 (최고 민감)
  'ops.operator_create': { label: '운영자 계정 생성', icon: 'ph-user-circle-plus', cls: 'warn' },
  'ops.operator_update': { label: '운영자 권한 변경', icon: 'ph-user-circle-gear', cls: 'warn' },
  'ops.operator_password_reset': { label: '운영자 비밀번호 재설정', icon: 'ph-key', cls: 'warn' },
  'ops.ai_model_create': { label: 'AI 모델 등록', icon: 'ph-cpu', cls: 'ok' },
  'ops.ai_model_update': { label: 'AI 모델 수정', icon: 'ph-cpu', cls: 'neutral' },
  // 기관 관리자 — 학년부장/학급
  'org.grade_head_appoint': { label: '학년부장 임명', icon: 'ph-user-circle-gear', cls: 'ok' },
  'org.grade_head_dismiss': { label: '학년부장 해임', icon: 'ph-user-circle-minus', cls: 'warn' },
  'org.class_create': { label: '학급 생성', icon: 'ph-plus-circle', cls: 'ok' },
  'org.class_dissolve': { label: '학급 해산', icon: 'ph-minus-circle', cls: 'no' },
  // 강사·운영자 — 코스
  'course.create': { label: '코스 생성', icon: 'ph-plus-circle', cls: 'ok' },
  'course.update': { label: '코스 수정', icon: 'ph-pencil-simple', cls: 'neutral' },
  'course.delete': { label: '코스 삭제', icon: 'ph-trash', cls: 'no' },
  'course.pricing.update': { label: '코스 수강료 설정', icon: 'ph-tag', cls: 'neutral' },
  'course.thumbnail': { label: '코스 커버 등록', icon: 'ph-image', cls: 'neutral' },
  'course.thumbnail_delete': { label: '코스 커버 삭제', icon: 'ph-image', cls: 'warn' },
  // 강사 — 강의
  'lecture.create': { label: '강의 업로드', icon: 'ph-upload-simple', cls: 'ok' },
  'lecture.update': { label: '강의 수정', icon: 'ph-pencil-simple', cls: 'neutral' },
  'lecture.reorder': { label: '강의 순서 변경', icon: 'ph-arrows-down-up', cls: 'neutral' },
  'lecture.trash': { label: '강의 삭제(휴지통)', icon: 'ph-trash', cls: 'no' },
  'lecture.restore': { label: '강의 복구', icon: 'ph-arrow-counter-clockwise', cls: 'ok' },
  'lecture.purge': { label: '강의 완전 삭제', icon: 'ph-trash', cls: 'no' },
  'lecture.thumbnail': { label: '강의 썸네일 등록', icon: 'ph-image', cls: 'neutral' },
  'lecture.thumbnail_delete': { label: '강의 썸네일 삭제', icon: 'ph-image', cls: 'warn' },
  'lecture.bot_check.passed': { label: '시청 봇 검증 통과', icon: 'ph-shield-check', cls: 'neutral' },
  'lecture.review.upsert': { label: '수강 후기 작성', icon: 'ph-star', cls: 'neutral' },
  // 강사 — 확인문항
  'lecture.question.create': { label: '확인문항 추가', icon: 'ph-plus-circle', cls: 'ok' },
  'lecture.question.update': { label: '확인문항 수정', icon: 'ph-pencil-simple', cls: 'neutral' },
  'lecture.question.delete': { label: '확인문항 삭제', icon: 'ph-trash', cls: 'no' },
  'lecture.question.generate': { label: '확인문항 AI 생성', icon: 'ph-sparkle', cls: 'ok' },
  'lecture.question.to_bank': { label: '확인문항 문제은행 배치', icon: 'ph-archive', cls: 'neutral' },
  'lecture.question.bulk_to_bank': { label: '확인문항 문제은행 일괄 배치', icon: 'ph-archive', cls: 'neutral' },
  'lecture.question.image.create': { label: '확인문항 이미지 첨부', icon: 'ph-image', cls: 'neutral' },
  'lecture.question.image.delete': { label: '확인문항 이미지 삭제', icon: 'ph-image', cls: 'warn' },
  'lecture.question.report': { label: '문항 신고', icon: 'ph-flag', cls: 'warn' },
  'lecture.question.report.resolve': { label: '문항 신고 처리', icon: 'ph-flag-checkered', cls: 'ok' },
  // 강사 — 수료시험 문항
  'course.exam_question.create': { label: '수료시험 문항 추가', icon: 'ph-plus-circle', cls: 'ok' },
  'course.exam_question.update': { label: '수료시험 문항 수정', icon: 'ph-pencil-simple', cls: 'neutral' },
  'course.exam_question.delete': { label: '수료시험 문항 삭제', icon: 'ph-trash', cls: 'no' },
  'course.exam_question.import_lectures': { label: '수료시험 문항 강의에서 가져오기', icon: 'ph-download-simple', cls: 'neutral' },
  'course.exam_question.import_bank': { label: '수료시험 문항 문제은행에서 가져오기', icon: 'ph-download-simple', cls: 'neutral' },
  'course.exam_question.generate': { label: '수료시험 문항 AI 생성', icon: 'ph-sparkle', cls: 'ok' },
  'course.exam_question.image.create': { label: '수료시험 문항 이미지 첨부', icon: 'ph-image', cls: 'neutral' },
  'course.exam_question.image.delete': { label: '수료시험 문항 이미지 삭제', icon: 'ph-image', cls: 'warn' },
  // 강사 — 자막/자료
  'lecture.transcript.set': { label: '강의 자막 저장', icon: 'ph-text-t', cls: 'neutral' },
  'lecture.transcript.upload': { label: '강의 자막 업로드', icon: 'ph-upload-simple', cls: 'neutral' },
  'lecture.transcript.delete': { label: '강의 자막 삭제', icon: 'ph-text-t', cls: 'warn' },
  'lecture.material.create': { label: '강의 자료 추가', icon: 'ph-paperclip', cls: 'ok' },
  'lecture.material.update': { label: '강의 자료 수정', icon: 'ph-pencil-simple', cls: 'neutral' },
  'lecture.material.delete': { label: '강의 자료 삭제', icon: 'ph-trash', cls: 'no' },
  // 운영자 — 강사/학생 계정
  'ops.instructor_create': { label: '강사 계정 생성', icon: 'ph-user-circle-plus', cls: 'warn' },
  'ops.instructor_update': { label: '강사 정보 수정', icon: 'ph-user-circle-gear', cls: 'neutral' },
  'ops.instructor_password_reset': { label: '강사 비밀번호 재설정', icon: 'ph-key', cls: 'warn' },
  'ops.student_password_reset': { label: '학생 비밀번호 재설정', icon: 'ph-key', cls: 'warn' },
  'ops.login_throttle_unlock': { label: '로그인 잠금 해제', icon: 'ph-lock-open', cls: 'warn' },
  // 운영자 — AI 런타임/시스템 설정
  'ops.ai_runtime.model_create': { label: 'AI 런타임 모델 등록', icon: 'ph-cpu', cls: 'ok' },
  'ops.ai_runtime.model_update': { label: 'AI 런타임 모델 수정', icon: 'ph-cpu', cls: 'neutral' },
  'ops.ai_runtime.model_delete': { label: 'AI 런타임 모델 삭제', icon: 'ph-cpu', cls: 'no' },
  'ops.ai_runtime.config': { label: 'AI 런타임 설정 변경', icon: 'ph-sliders-horizontal', cls: 'neutral' },
  'system.settings.ai_keys': { label: 'AI API 키 설정', icon: 'ph-key', cls: 'warn' },
  'system.settings.ai_prompt': { label: 'AI 생성 프롬프트 변경', icon: 'ph-text-aa', cls: 'neutral' },
  'system.settings.ai_verify_prompt': { label: 'AI 검증 프롬프트 변경', icon: 'ph-text-aa', cls: 'neutral' },
  // 운영자 — 행동 데이터
  'behavior.label_mark': { label: '행동 데이터 라벨 변경', icon: 'ph-tag', cls: 'neutral' },
  'behavior.redteam_generate': { label: '레드팀 데이터 생성', icon: 'ph-sparkle', cls: 'neutral' },
};

/** 대상(target_type) 내부 코드 → 사람이 읽는 라벨 */
export const AUDIT_TARGET_LABEL: Record<string, string> = {
  organization: '기관',
  org_registration_request: '기관 가입신청',
  membership: '구성원',
  user: '사용자',
  user_setting: '계정 설정',
  student: '학생',
  student_profile: '학생',
  parent_student_link: '학부모 연결',
  invitation: '초대',
  join_code: '가입코드',
  class: '학급',
  api_key: 'API 키',
  captcha_setting: '캡차 설정',
  behavior_summary: '행동 데이터',
  model_version: 'AI 모델',
  inquiry: '문의',
  course: '코스',
  lecture: '강의',
  lecture_question: '확인문항',
  course_exam_question: '수료시험 문항',
  lecture_material: '강의 자료',
  lecture_transcript: '강의 자막',
  lecture_question_report: '문항 신고',
};
